"""The mandatory call seam between sanitized input and a model provider."""

from __future__ import annotations

from covenia_b.domain.types import CandidateExtraction
from covenia_b.ports.contracts import ModelProvider
from covenia_b.privacy.sanitizer import SanitizationResult, redact_text


class UnsafeModelInputError(ValueError):
    """Raised before a provider can capture an untrusted model projection."""


async def extract_with_privacy_boundary(
    provider: ModelProvider,
    prepared_input: SanitizationResult,
) -> CandidateExtraction:
    """Dispatch only the safe model-input projection through the provider port.

    The boundary first requires the exact projection generated by the privacy
    sanitizer, including its safe source-ID provenance.  A secondary text scan
    remains a defense-in-depth check for detectable in-place regressions.
    """

    _reject_detectable_raw_pii(prepared_input)
    return await provider.extract(prepared_input.model_input)


def _reject_detectable_raw_pii(prepared_input: SanitizationResult) -> None:
    if (
        not isinstance(prepared_input, SanitizationResult)
        or not prepared_input._has_generated_projection()
    ):
        raise UnsafeModelInputError("unsafe unredacted model input was blocked")

    probe = redact_text(prepared_input.model_input.redacted_text)
    if probe.pii_masked_count:
        raise UnsafeModelInputError("unsafe unredacted model input was blocked")
