// Local, bounded conversation simulation for the three competition cases.
// These lines are not consumer messages from Qianniu and are not generated by JEV.
export function simulateConsumerReply(caseId: string, agentReply: string, turn: number): string | null {
  const reply = agentReply.replace(/\s+/g, "");
  // Two customer turns are enough to demonstrate a changing conversation.
  // A scripted consumer must not keep repeating itself after every send.
  if (turn >= 2) return null;
  const asksForMoreEvidence = reply.split(/[，。；;]/).some((clause) =>
    /(请|麻烦|需要|必须|先).{0,12}(再上传|再发|重传|整单|全部照片|所有照片)/.test(clause)
    && !/(不用|无需|不必|不要|不需要).{0,12}(再上传|再发|重传|整单|全部照片|所有照片)/.test(clause),
  );

  if (caseId === "DEMO_001") {
    if (asksForMoreEvidence) return "泵头的照片我已经发过了，能先查一下换货进度吗？";
    if (turn === 0) {
      return /揽收|换货|物流|进度|仓库|更新/.test(reply)
        ? "好，照片不用再发了。那请到约定时间主动告诉我，换货件有没有揽收。"
        : "我最想知道的是换货现在到哪一步了，能帮我查一下吗？";
    }
    if (turn === 1) {
      return /已经揽收|已发出|已送达/.test(reply)
        ? "收到，谢谢。后续如果物流有变化，也麻烦及时告诉我。"
        : "明白。下次更新大约是什么时候？我不想再反复来问了。";
    }
  }

  if (caseId === "DEMO_002") {
    if (asksForMoreEvidence) return "我已经发过照片了。能不能只告诉我精华瓶口还缺哪张，不要整单重传？";
    if (turn === 0) {
      return /精华|瓶口|裂痕|近照|这一张|一张/.test(reply)
        ? "明白，只补精华瓶口这一张。我拍好就发，不用重传整个订单对吗？"
        : "我发的赠品照片你们看到了吗？现在到底还需要我补什么？";
    }
    if (turn === 1) {
      return /不用|无需|不必/.test(reply)
        ? "好，那我只拍精华瓶口。发过去以后你们会继续处理这件商品吧？"
        : "好的，麻烦说清楚只需要哪张照片，我按这个补。";
    }
  }

  if (caseId === "DEMO_003") {
    if (/面部照片|脸部照片|拍脸|继续使用/.test(reply) && !/不用|无需|不必|暂停/.test(reply)) {
      return "我现在不想在聊天里发面部照片，可以先转给专人吗？";
    }
    if (turn === 0) {
      return /专人|人工|复核|暂停/.test(reply)
        ? "好的，我先暂停使用。面部照片可以先不发吧？请问专人什么时候联系我？"
        : "我现在脸还在发红，能先请专人帮我看一下吗？";
    }
    if (turn === 1) {
      return /联系|时间|回复/.test(reply)
        ? "明白，我等专人联系；如果情况有变化我会再告诉你们。"
        : "谢谢，请帮我确认是谁接手，什么时候能有下一步回复。";
    }
  }

  return "收到。请告诉我下一步会怎么处理，以及什么时候更新。";
}
